[book]
authors = ["Martin Geisler", "adapted by Cristel Pelsser"]
language = "en"
src = "src"
title = "Rust-LINFO2315"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.links]
renderers = ["html"]

[preprocessor.index]
renderers = ["html"]

[preprocessor.svgbob]
renderers = ["html"]
class = "bob"

# Enable this preprocessor to overlay a large red rectangle on the
# pages. This will show you an estimate of what the course
# participants can see during the presentation.
#
# [preprocessor.aspect-ratio-helper]
# command = "./aspect-ratio-helper.py"

[output.html]
smart-punctuation = true
default-theme = "navy"
preferred-dark-theme = "navy"
additional-js = ["speaker-notes.js"]
additional-css = ["svgbob.css", "speaker-notes.css"]
site-url = "/"
git-repository-url = "https://github.com/cpelsser/rust-mdbook"
edit-url-template = "https://github.com/cpelsser/rust-mdbook/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.pandoc]
optional = true
disabled = true
hosted-html = "https://cpelsser.github.io/rust-mdbook/"

[output.pandoc.profile.pdf]
output-file = "linfo2315-rust-course.pdf"
pdf-engine = "lualatex"

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = [
  "NotoColorEmoji:mode=harf",
  "NotoSansMath:",
]
sansfontfallback = [
  "NotoColorEmoji:mode=harf",
]
monofontfallback = [
  "NotoColorEmoji:mode=harf",
  "NotoSansMath:",
]
geometry = ["margin=1.25in"]
linkcolor = "blue"
urlcolor = "red"
